# Generated by Django 4.2.10 on 2026-04-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_time', models.TimeField(default='08:00')),
                ('end_time', models.TimeField(default='17:00')),
                ('slot_duration', models.IntegerField(default=30, help_text='Minutes per appointment slot')),
                ('buffer_time', models.IntegerField(default=10, help_text='Buffer minutes between slots')),
                ('max_per_day', models.IntegerField(default=10, help_text='Maximum appointments per day')),
                ('lunch_start', models.TimeField(blank=True, help_text='Lunch break start (optional)', null=True)),
                ('lunch_end', models.TimeField(blank=True, help_text='Lunch break end (optional)', null=True)),
            ],
            options={
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.TextField(help_text='Purpose / agenda of the meeting')),
                ('organization', models.CharField(blank=True, default='', max_length=200)),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP / Priority')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('rescheduled_date', models.DateField(blank=True, null=True)),
                ('rescheduled_time', models.TimeField(blank=True, null=True)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('reminder_24h_sent', models.BooleanField(default=False)),
                ('reminder_1h_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'time_slot'],
                'unique_together': {('date', 'time_slot')},
            },
        ),
    ]
